# HQMX Backend Docker Compose
version: '3.8'

services:
  # HQMX Backend 서비스
  hqmx-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hqmx-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - /tmp/hqmx:/tmp/hqmx
    depends_on:
      - redis
    networks:
      - hqmx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis 서비스 (선택사항)
  redis:
    image: redis:7-alpine
    container_name: hqmx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hqmx-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: hqmx-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - hqmx-backend
    networks:
      - hqmx-network

volumes:
  redis-data:
    driver: local

networks:
  hqmx-network:
    driver: bridge